// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYAfysdtxLJOkaWsnGulbRAtTXCoHedJo',
    appId: '1:240616993266:web:2a856e78f1d14152fabb6b',
    messagingSenderId: '240616993266',
    projectId: 'deco-8b294',
    authDomain: 'deco-8b294.firebaseapp.com',
    storageBucket: 'deco-8b294.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgMDUv_AC6fV2noilf06m3BMjkmZb1y1I',
    appId: '1:240616993266:android:42265d3218d835d1fabb6b',
    messagingSenderId: '240616993266',
    projectId: 'deco-8b294',
    storageBucket: 'deco-8b294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9C5_cmcRI5UwDfjx2dXACimihFHo4Xsw',
    appId: '1:240616993266:ios:70113b4263edbffdfabb6b',
    messagingSenderId: '240616993266',
    projectId: 'deco-8b294',
    storageBucket: 'deco-8b294.firebasestorage.app',
    iosBundleId: 'com.jikyunghee.deco',
  );

}